### ISSUE TITLE
64 bit nexus 9

### ISSUE THREAD

**Issue by edjones99** [zhuowei/Boardwalk#113] opened 2015-02-01 05:55 UTC
Version of Boardwalk: 1.06

Version of Android: 5.01

Device model: Nexus 9

Description of the problem: Doesn't work with nexus 9. Probably because the device is 64 bit.

**Comment by joho506** [comment] 2015-02-01 11:37
"Doesn't work" in what manner?

**Comment by zhuowei** [comment] 2015-02-02 01:48
duplicate of #66

**Closed by zhuowei** 2015-02-02 01:48 UTC
