### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by WarrioR151** [zhuowei/Boardwalk#144] opened 2015-03-01 17:03 UTC
Version of Boardwalk: 1.1

Version of Android: 4.1.1

Device model: SENCOR ELEMENT 9.7 v3

Description of the problem: Java problem here is screen 
![screenshot_2015-03-01-18-02-31](https://cloud.githubusercontent.com/assets/11258616/6431823/36b5e05e-c03d-11e4-8f37-7ed60eeb38be.png)

**Comment by WarrioR151** [comment] 2015-03-08 08:59
Omg can you help me ??????

**Comment by joho506** [comment] 2015-03-08 11:44
Go search the rest of the issues for 'dex returned 11 with error'. It's
been mentioned before.

**Comment by zhuowei** [comment] 2015-03-09 06:22
duplicate of #25

**Closed by zhuowei** 2015-03-09 06:22 UTC
