### ISSUE TITLE
Incorrect JavaCrypto Library on 64 bit Devices

### ISSUE THREAD

**Issue by ZCodeMT** [zhuowei/Boardwalk#93] opened 2015-01-04 23:52 UTC
When attempting to run on a 64 bit device, Boardwalk fails to load libjavacrypto.so because it tries to load the 32 bit version of the library. I'm guessing it's probably a call of `System.load("/system/lib/libjavacrypto.so")` which should be `System.loadLibrary("javacrypto")`. I'm using the Nexus 9.

**Comment by zhuowei** [comment] 2015-01-05 01:36
dupe of #66

**Closed by zhuowei** 2015-01-05 01:36 UTC
