### ISSUE TITLE
dex returned 11

### ISSUE THREAD

**Issue by Eduardo19k** [zhuowei/Boardwalk#100] opened 2015-01-09 23:01 UTC
Version of Boardwalk:1.0.7

Version of Android:4.0.4

Device model:Metapad c32

Description of the problem: Error: java.lang.RuntimeException:java.lang.RuntimeException:Dex returned 11 with error:

**Comment by zhuowei** [comment] 2015-01-10 03:08
Duplicate of #31. Sorry!

**Closed by zhuowei** 2015-01-10 03:08 UTC
