### ISSUE TITLE
Game doesn't start on Nexus 9

### ISSUE THREAD

**Issue by kylersmith7** [zhuowei/Boardwalk#102] opened 2015-01-12 03:39 UTC
Version of Boardwalk: 1.0.6
![screenshot_2015-01-11-14-54-00](https://cloud.githubusercontent.com/assets/5760465/5698726/8f9412a8-99c9-11e4-8a8f-dee67d3c02c6.png)

Version of Android: 5.0.1

Device model: Nexus 9

Description of the problem: Error

**Comment by joho506** [comment] 2015-01-25 14:26
Giving a more descriptive title may help, such as 'Game doesn't open on Nexus 9'.

**Comment by zhuowei** [comment] 2015-02-02 01:48
duplicate of #66

**Closed by zhuowei** 2015-02-02 01:48 UTC
