### ISSUE TITLE
Boardwalk issue when downloading files

### ISSUE THREAD

**Issue by Jaakow22** [zhuowei/Boardwalk#139] opened 2015-02-24 13:57 UTC
Version of Boardwalk: 1.1
Version of Android: 4.2.2
Device model: Tele2fon v5 (rebranded Mobiwire Auriga with 1GB of RAM, MediaTek MT6572)
Description of the problem: After I logged on and pressed launch game when downloading com.mojang:realms:1.3.5 it gets interrupted and I get this error java.lang.RuntimeException: java.lang.RuntimeException: Dex Returned 11 with error:

Here are the screenshots: 
https://www.dropbox.com/sh/xyvjx762yggxmd4/AAD4MadG2nd5MztlXCwVCqkDa?dl=0

**Comment by zhuowei** [comment] 2015-02-24 16:19
Duplicate of #25.

**Closed by zhuowei** 2015-02-24 16:19 UTC
